config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      
      resources :users, only: [:create] do
        collection do
          post :login
        end
      end

      resources :polls do
        collection do
          post :vote
        end
      end
      
    end
  end

  root to: 'home#index'
  get '*path', to: 'home#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 4, maximum: 128 }
  validates :option1, presence: true, length: { minimum: 1, maximum: 64 }
  validates :option2, presence: true, length: { minimum: 1, maximum: 64 }
  validates :option3, presence: true, length: { minimum: 1, maximum: 64 }
  validates :option4, presence: true, length: { minimum: 1, maximum: 64 }

  def poll_result
    sum = ( option1_votes + option2_votes + option3_votes + option4_votes ).to_f
    {
      option1_percent: vote_percent(sum, option1_votes),
      option2_percent: vote_percent(sum, option2_votes),
      option3_percent: vote_percent(sum, option3_votes),
      option4_percent: vote_percent(sum, option4_votes)
    }
  end

  def vote_percent(sum, option)
    ((option.to_f / sum) * 100.00).round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :polls
  
  before_validation :normalize_email

  validates :first_name, presence: true, length: {minimum:3, maximum:16}
  validates :last_name, presence: true, length: {minimum:3, maximum:16}
  validates :email, uniqueness: { message: "duplicate" },
                  presence: true,
                  length: { maximum: 50 },
                  format: { with: URI::MailTo::EMAIL_REGEXP
                }
  validates :password, presence: true, length: { in: Devise.password_length }
  validates :password_confirmation, { presence: { case_sensitive: true } }

  private

  def normalize_email
    email = email.downcase.strip if email.present?
  end

end

app/controllers/api/v1/polls_controller.rb
class Api::V1::PollsController < ApplicationController
  before_action :require_auth, only: %i[ create edit update destroy vote ]
  before_action :require_poll, only: %i[ edit update destroy show vote ]

  attr_accessor :poll

  def index
    polls = Poll.all
    render json: { success: true, polls: polls }
  end

  def show
    render json: { success: true, poll: poll }
  end

  def update
    updated_poll = poll.update(poll_params)
    render json: { success: false, notice: "Unable to update" }  unless updated_poll
    render json: { success: true, notice: "Poll successfully updated" }
  end

  def create
    poll = current_user.polls.create!(poll_params)
    unless poll
      render json: { success: false }
    end
    render json: {  success: true, notice: "Poll successfully created" }
  end

  def destroy
    if poll.destroy
      render json: { success: true, notice: "Poll deleted" }
    end
  end

  def vote
    unless [1, 2, 3, 4].include? vote_params[:option]
      render json: { success: false, notice: "Wrong option" }
    end
    option = "option#{vote_params[:option]}_votes".to_sym
    poll.increment!(option)
    poll_result = poll.poll_result
    render json: { success: true, result: poll_result } if poll_result.present?
  end

  private

  def require_poll
    set_poll
    return if poll.present?
    render json: { success: false, notice: "Poll not found" }
  end

  def set_poll
    poll_id = params[:id] || params[:poll][:id]
    @poll = Poll.find(poll_id)
  end

  def poll_params
    params.require(:poll).permit(:title, :option1, :option2, :option3, :option4)
  end

  def vote_params
    params.require(:poll).permit(:id, :option)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  extend Devise::Models

    def create
      user = User.new(user_params)
      if user.valid?
        user.save
        render :ok, json: { success: true, notice: "Successfully registered" }
      else 
        render :bad_request, json: { success: false, notice: "Invalid input" }
      end
    end

    def login
      user = User.find_by!(email: user_params[:email])
      render status: :unauthorized, json: { success: false, notice: "User not found" } unless user.present?
      if  user.authenticate(user_params[:password])
        token = Auth.create_token user.id 
        render :ok, json: {  success: true, user_first_name: user.first_name, auth_token: token }
      else
        render :unauthorized, json: { success: false, notice: "Invalid credentials" }  
      end
    end
    
    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    attr_accessor :current_user
    before_action :set_current_user

    rescue_from ActiveRecord::RecordNotFound, with: :resources_not_avalable
    rescue_from RuntimeError, with: :server_side_error

    skip_before_action :verify_authenticity_token
    
    private

    def require_auth
      return if current_user.present?
      render :unauthorized, json: { success: false, notice: "Unauthorized" }
    end

    def set_current_user
      token = request.headers["X-Auth-Token"]
      user_id = Auth.user_id_from_jwt token
      @current_user = User.find(user_id) rescue nil
    end

    def resources_not_avalable(err)
      render status: :bad_request, json: { success: false, notice: "Resource not avalable" }
    end

    def server_side_error
      render status: :internal_server_error, json: { success: false, notice: "Something went wrong" }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= csrf_meta_tags %>
<%= react_component 'App' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/polls/_form.html.erb
<%= form_with(model: poll, local: true) do |form| %>
  <% if poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
        <% poll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>